"""add_presentation_links_table

Revision ID: 8c6816d35a0f
Revises: 99663262ac68
Create Date: 2026-08-18 14:40:24.986908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c6816d35a0f'
down_revision: Union[str, None] = '99663262ac68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentation_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_presentation_links_expires', 'presentation_links', ['expires_at'], unique=False)
    op.create_index('idx_presentation_links_file', 'presentation_links', ['file_id', 'created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_presentation_links_file', table_name='presentation_links')
    op.drop_index('idx_presentation_links_expires', table_name='presentation_links')
    op.drop_table('presentation_links')
    # ### end Alembic commands ###
